#!/usr/bin/env bash
set -euo pipefail

AUTOWEB_ROOT=${AUTOWEB_ROOT:-/srv/autoweb}
INFRA_DIR=${INFRA_DIR:-${AUTOWEB_ROOT}/current/infra/upcloud}
HOST_ENV=${HOST_ENV:-${AUTOWEB_ROOT}/secrets/host.env}
APP_ENV=${APP_ENV:-${AUTOWEB_ROOT}/secrets/app.env}

fail() {
  echo "[preflight] $*" >&2
  exit 1
}

[[ -f ${HOST_ENV} ]] || fail "Missing ${HOST_ENV}"
[[ -f ${APP_ENV} ]] || fail "Missing ${APP_ENV}"

for secret_file in "${HOST_ENV}" "${APP_ENV}"; do
  mode=$(stat -c '%a' "${secret_file}")
  [[ ${mode} == "600" ]] || fail "${secret_file} must have mode 600, found ${mode}"
done

set -a
# host.env is generated by this runbook and contains shell-safe values.
source "${HOST_ENV}"
set +a

for required in APP_RELEASE_SHA POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD ACME_EMAIL PREVIEW_ALLOWED_CIDRS ALERT_EMAIL; do
  [[ -n ${!required:-} ]] || fail "${required} is required in host.env"
done
[[ ${APP_RELEASE_SHA} =~ ^[0-9a-f]{40}$ ]] || fail "APP_RELEASE_SHA must be a full Git SHA"
[[ ${POSTGRES_PASSWORD} =~ ^[0-9a-fA-F]{64}$ ]] || fail "POSTGRES_PASSWORD must be 64 hexadecimal characters"

for forbidden in DATABASE_URL REDIS_URL API_BASE_URL API_PORT PORT GENERATION_LOG_DATABASE_URL START_WORKER NEWSWEB_POLLING_ENABLED NODE_OPTIONS; do
  if grep -qE "^${forbidden}=" "${APP_ENV}"; then
    fail "${forbidden} must not be present in app.env"
  fi
done

for required in ADMIN_API_KEY LOGIN_PASSWORD LOGIN_USERNAME MAGIC_LINK_BASE_URL SESSION_SECRET; do
  grep -qE "^${required}=.+" "${APP_ENV}" || fail "${required} must be populated in app.env"
done
grep -qE '^MAGIC_LINK_BASE_URL=https://autoweb24\.no/login$' "${APP_ENV}" || fail "MAGIC_LINK_BASE_URL must use the production canonical URL"
if ! grep -qE '^(OPENAI_API_KEY|LITELLM_API_KEY|ANTHROPIC_API_KEY)=.+' "${APP_ENV}"; then
  fail "At least one model-provider credential must be populated"
fi

command -v docker >/dev/null || fail "Docker is not installed"
docker compose version >/dev/null || fail "Docker Compose plugin is not installed"

memory_kib=$(awk '/MemTotal:/ {print $2}' /proc/meminfo)
(( memory_kib >= 15000000 )) || fail "Host has less than the expected 15 GiB usable RAM"
swap_kib=$(awk '/SwapTotal:/ {print $2}' /proc/meminfo)
(( swap_kib >= 3500000 )) || fail "Host has less than 3.5 GiB swap"
free_kib=$(df -Pk "${AUTOWEB_ROOT}" | awk 'NR==2 {print $4}')
(( free_kib >= 25000000 )) || fail "Host has less than 25 GiB free disk"

for component in api worker web; do
  image="autoweb-${component}:${APP_RELEASE_SHA}"
  docker image inspect "${image}" >/dev/null || fail "Missing image ${image}"
  revision=$(docker image inspect --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' "${image}")
  [[ ${revision} == "${APP_RELEASE_SHA}" ]] || fail "${image} revision label does not match APP_RELEASE_SHA"
done

docker compose --env-file "${HOST_ENV}" -f "${INFRA_DIR}/compose.yml" config --quiet
echo "[preflight] PASS release=${APP_RELEASE_SHA}"
